services:
  mongo:
    image: mongo
    volumes:
      - ./data/runtime/db:/data/db
      - ./data/dump:/dump
    command: mongod --smallfiles --oplogSize 128

  rocketchat:
    image: rocketchat/rocket.chat:latest
    volumes:
      - ./uploads:/app/uploads
    environment:
      - PORT=3000
      - ROOT_URL=http://rc.telecard.com.ua:8066
      - MONGO_URL=mongodb://mongo:27017/rocketchat
    links:
      - mongo:mongo



  nginx:
    image: nginx:1.10.1-alpine
    volumes:
      - ./certs/cert.crt:/etc/nginx/cert.crt
      - ./certs/cert.key:/etc/nginx/cert.key
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    links:
      - rocketchat:rocketchat
    ports:
      - 8066:443
