mongo:
  image: mongo
  volumes:
    - ./data/runtime/db:/data/db
    - ./data/dump:/dump
  command: mongod --smallfiles --oplogSize 128

rocketchat:
  image: rocketchat/rocket.chat:latest
  volumes:
    - ./uploads:/app/uploads
  environment:
    - PORT=3000
    - ROOT_URL=http://rc.telecard.com.ua:8066
    - MONGO_URL=mongodb://mongo:27017/rocketchat
  links:
    - mongo:mongo
    - smtp:smtp


smtp:
  image: namshi/smtp
  environment:
    - RELAY_DOMAINS=:telecard.com.ua

nginx:
  image: nginx:1.10.1-alpine
  volumes:
    - ./certs/cert.crt:/etc/nginx/cert.crt
    - ./certs/cert.key:/etc/nginx/cert.key
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  links:
    - rocketchat:rocketchat
  ports:
    - 8066:443
nginx.conf
events {
  worker_connections  1024;
}

http {
  server {

    listen 443;
    server_name host.example.com;

    ssl_certificate           /etc/nginx/cert.crt;
    ssl_certificate_key       /etc/nginx/cert.key;

    ssl on;
    ssl_session_cache  builtin:1000  shared:SSL:10m;
    ssl_protocols  TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers HIGH:!aNULL:!eNULL:!EXPORT:!CAMELLIA:!DES:!MD5:!PSK:!RC4;
    ssl_prefer_server_ciphers on;

    access_log            /var/log/nginx/rocketchat.access.log;

    location / {

      proxy_set_header        Host $host;
      proxy_set_header        X-Real-IP $remote_addr;
      proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header        X-Forwarded-Proto $scheme;

      # Fix the “It appears that your reverse proxy set up is broken" error.
      proxy_pass          http://rocketchat:3000;
      proxy_read_timeout  90;

      proxy_redirect      http://rocketchat:3000 https://host.example.com;
    }
  }
}