version: 2.1
jobs:
  build:
    docker:
      - image: cirleci/golang:1.15
        auth:
          username: bwhugo
          password: $DOCKHUB_PASSWORD
    steps:
      - checkout

      - setup_remote_docker:
        version: 19.03.13


      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t bwhugo/circleci-demo-docker:$TAG .
          docker login -u bwhugo -p $DOCKHUB_PASSWORD
          docker push bwhugo/circleci-demo-docker:$TAG